// Pre-build step: read React Flow's stylesheet and emit it as a TS string module,
// so the bundler never has to process CSS (avoids inheriting the host's PostCSS/
// Tailwind config). The result is inlined into dist/erd.js by tsup.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cssPath = join(here, "..", "node_modules", "@xyflow", "react", "dist", "style.css");
const outPath = join(here, "..", "src", "generated", "xyflowCss.ts");

const css = readFileSync(cssPath, "utf8");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/inline-css.mjs — do not edit.\nexport const xyflowCss = ${JSON.stringify(css)};\n`,
  "utf8",
);
console.log(`inlined @xyflow/react CSS (${css.length} bytes) -> src/generated/xyflowCss.ts`);
