apiVersion: v2
name: mapping-metadata-platform
description: Mapping and Metadata Platform — enterprise metadata management & governance control plane
type: application
version: 0.1.0
appVersion: "0.1.0"
